# City name
city: Washington, DC, USA
# City centerpoint latitude & longitude
city_latitude: 38.9071923
city_longitude: -77.0368707
timezone: America/New_York
# Radius of city's road network from centerpoint in km (required if OSM has no polygon data)
city_radius: 25
# The folder under data where this city's data is stored
name: dc
# If given, limit crashes to after startdate and no later than enddate
# Recommended to limit to just a few years for now
startdate: 2014-01-01
enddate: 2016-12-31

#################################################################
# Configuration for data standardization

# crash file configurations
crashes_files:
  Crashes_in_DC.csv:
    required:
      id: OBJECTID
      latitude: Y
      longitude: X
      # If date supplied in single column:
      date_complete: REPORTDATE
      # If date is separated into year/month/day:
      date_year: 
      date_month: 
      # Leave date_day empty if not available
      date_day: 
      # If time is available and separate from date:
      time: 
      # If time specified, time_format is one of:
      # default (HH:MM:SS)
      # seconds (since midnight)
      # military (HHMM)
      time_format: 
    optional:
      summary: MAR_ADDRESS
      split_columns:
        pedestrian:
          column_name: TOTAL_PEDESTRIANS
          column_value: any
        bike:
          column_name: TOTAL_BICYCLES
          column_value: any
        vehicle:
          column_name: TOTAL_VEHICLES
          column_value: any

#################################################################
# Configuration for default features

# Default features from open street map. You can remove features you don't want
# Note: we don't support adding features in the config file.
# If there is an additional feature you want from open street map, contact the development team
openstreetmap_features:
  categorical:
    width: Width
    cycleway_type: Bike lane
    oneway: One Way
    lanes: Number of lanes
  continuous:
    width_per_lane: Average width per lane


data_source:
- name: visionzero
  filename: Vision_Zero_Safety.csv
  latitude: Y
  longitude: X
  date: REQUESTDATE
